// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:4a8a3404-c5e8-48fc-8871-4c1c59aa7be4",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Mbmfrv0sf",
    "aws_user_pools_web_client_id": "41adi60t44faht2gn0jlu7pbde"
};


export default awsmobile;
